from pydantic import BaseModel, Field
from typing import List, Optional

# Synthetic household profile used only for guidance computation (not persisted)
class HouseholdProfile(BaseModel):
    """Demographic and preference data for a synthetic demo household."""
    language: str = Field(..., description="ISO language code, e.g., 'en', 'hi', 'od'")
    household_size: int = Field(..., ge=1, description="Number of people in the household")
    children: int = Field(..., ge=0, description="Number of children (<18)")
    elderly: int = Field(..., ge=0, description="Number of elderly (>65)")
    mobility_needs: bool = Field(..., description="Presence of mobility impairments requiring accessible routes")
    vehicle_access: bool = Field(..., description="Household has a vehicle for evacuation")
    preferred_facility_type: str = Field(..., description="e.g., 'shelter', 'hospital', 'school' – used for filtering")
    selected_location: str = Field(..., description="Latitude,Longitude as string or named region identifier")

class GuidanceAssumption(BaseModel):
    key: str = Field(..., description="Assumption identifier")
    description: str = Field(..., description="Human‑readable description of the assumption used")

class PersonalizedGuidanceResponse(BaseModel):
    language: str = Field(..., description="Response language code matching the profile")
    recommended_destination: Optional[dict] = Field(None, description="Serialized DestinationCandidate from safe‑destination engine")
    recommended_route: Optional[dict] = Field(None, description="Serialized EvacuationRoute from routing engine")
    assumptions: List[GuidanceAssumption] = Field(..., description="List of applied assumptions for transparency")
    message: str = Field(..., description="Human‑readable guidance generated by Gemini (placeholder)")
    data_freshness_minutes: Optional[int] = Field(None, description="Age of the underlying data used")
