from pydantic import BaseModel, Field
from typing import List, Optional, Literal
from datetime import datetime

class SystemState(BaseModel):
    """Snapshot of the overall disaster‑intelligence system at a point in time."""
    timestamp: datetime = Field(..., description="When this state was recorded (UTC).")
    rainfall_mm: Optional[float] = Field(None, description="Accumulated rainfall in millimetres.")
    wind_kmh: Optional[float] = Field(None, description="Maximum sustained wind speed (km/h).")
    hazard: Optional[str] = Field(None, description="Current hazard identifier, e.g., 'Cyclone‑23'.")
    population_exposure: Optional[int] = Field(None, description="Number of people exposed to the hazard.")
    road_accessibility: Optional[dict] = Field(
        None,
        description="Mapping of road IDs to a reliability score (0‑1)."
    )
    shelter_occupancy: Optional[dict] = Field(
        None,
        description="Mapping of shelter IDs to occupancy percentage (0‑100)."
    )
    infrastructure_risk: Optional[dict] = Field(
        None,
        description="Mapping of infrastructure IDs to risk level (e.g., 'low', 'moderate', 'high')."
    )
    recommended_destination: Optional[str] = Field(None, description="Destination ID chosen by the safe‑destination engine.")
    recommended_route: Optional[str] = Field(None, description="Route ID chosen by the routing engine.")
    alerts: Optional[List[str]] = Field(None, description="List of active alert identifiers.")

class DeltaEntry(BaseModel):
    """Single change between two system states."""
    metric: str = Field(..., description="Name of the tracked metric, e.g., 'rainfall_mm'.")
    previous: Optional[str] = Field(None, description="Human‑readable previous value.")
    current: Optional[str] = Field(None, description="Human‑readable current value.")
    change_indicator: Literal['↑', '↓', '=', '⊕', '⊖'] = Field(..., description="Arrow indicating increase, decrease or other change.")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="When the change was detected.")
    reason: Optional[str] = Field(None, description="If known, why the change occurred.")
    source: Optional[str] = Field(None, description="Provenance of the data (sensor, model, etc.).")

class StateChangeResponse(BaseModel):
    """Full diff payload returned to the frontend."""
    deltas: List[DeltaEntry]
    summary: Optional[str] = Field(None, description="Natural‑language summary generated by Gemini.")
    generated_at: datetime = Field(default_factory=datetime.utcnow, description="When the response was created.")
